apiVersion: v1
kind: Service
metadata:
  name: haproxy
spec:
  type: LoadBalancer
  selector:
    app: haproxy
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
    - name: stats
      protocol: TCP
      port: 8404
      targetPort: 8404

