apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-config
data:
  haproxy.cfg: |
    global
      log stdout format raw daemon
      maxconn 4096

    defaults
      mode http
      timeout connect 5s
      timeout client 30s
      timeout server 30s

    frontend http_front
      bind *:80
      default_backend apps_backend

    backend apps_backend
      balance roundrobin
      option httpchk GET /
      server gradleapp gradle-app-service.default.svc.cluster.local:3000 check inter 5000 rise 2 fall 3
      server springboot spring-boot-service.default.svc.cluster.local:8080 check inter 5000 rise 2 fall 3

